import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/nav-bar";
import LoginForm from "./components/login-form";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>{children}</body>
    </html>
  );
  // return (
  //   <div>
  //     <div>
  //       <Navbar />
  //     </div>
  //     <div className={inter.className}>{children}</div>
  //   </div>
  // );
}
